# Generated by Django 5.0 on 2023-12-29 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_contact_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='time',
        ),
    ]
